# Generated by Django 4.2.10 on 2026-01-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(blank=True, db_index=True, max_length=500)),
                ('title_en', models.CharField(blank=True, db_index=True, max_length=500)),
                ('title_jp', models.CharField(blank=True, max_length=500)),
                ('shikimori_id', models.IntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('anilist_id', models.IntegerField(blank=True, null=True)),
                ('mal_id', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500)),
                ('anime_type', models.CharField(choices=[('tv', 'TV Сериал'), ('movie', 'Фильм'), ('ova', 'OVA'), ('ona', 'ONA'), ('special', 'Спешл')], default='tv', max_length=20)),
                ('status', models.CharField(choices=[('ongoing', 'Онгоинг'), ('finished', 'Завершён'), ('announced', 'Анонсирован')], default='finished', max_length=20)),
                ('episodes', models.IntegerField(blank=True, null=True)),
                ('aired_from', models.DateField(blank=True, null=True)),
                ('aired_to', models.DateField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, db_index=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('scored_by', models.IntegerField(default=0)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('popularity', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('description_source', models.CharField(blank=True, max_length=100)),
                ('poster_url', models.URLField(blank=True, max_length=1000)),
                ('poster_file', models.ImageField(blank=True, null=True, upload_to='anime/posters/')),
                ('data_source', models.CharField(default='shikimori', max_length=100)),
                ('approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('genres', models.ManyToManyField(blank=True, related_name='anime', to='anime.genre')),
                ('studios', models.ManyToManyField(blank=True, related_name='anime', to='anime.studio')),
            ],
            options={
                'ordering': ['-popularity', '-score'],
                'indexes': [models.Index(fields=['title_ru'], name='anime_anime_title_r_1450af_idx'), models.Index(fields=['title_en'], name='anime_anime_title_e_2e763f_idx'), models.Index(fields=['year'], name='anime_anime_year_38d697_idx'), models.Index(fields=['status'], name='anime_anime_status_6458e9_idx'), models.Index(fields=['score'], name='anime_anime_score_fc3b7f_idx')],
            },
        ),
    ]
