# Generated by Django 4.2.10 on 2026-01-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_anime_search_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='trailer_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
