# Generated by Django 4.2.10 on 2026-01-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_anime_trailer_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='screenshots',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
