# Generated by Django 4.2.10 on 2026-01-17 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dubs', '0002_dub_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='dubgroup',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dubgroup',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dubgroup',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'На проверке'), ('verified', 'Верифицирована'), ('rejected', 'Отклонена')], default='pending', max_length=20),
        ),
    ]
